version: "3" 
services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'gitlab'
    ports:  
      - '81:80'
      - '443:443'
      - '22:22'
    volumes:
      - '~/devops/devops/srv/gitlab/config:/etc/gitlab' 
      - '~/devops/devops/srv/gitlab/logs:/var/log/gitlab'
      - '~/devops/devops/srv/gitlab/data:/var/opt/gitlab'
  jenkins: 
    image: 'jenkins/jenkins:latest'
    ports: 
    - '8082:8080'
    - '50000:50000'
    volumes: 
    - '~/unit-test-sample/jenkins:/var/jenkins_home'
    - '/var/run/docker.sock:/var/run/docker.sock'
    - '/usr/local/bin/docker:/usr/bin/docker'
  sonarqube:
    image: sonarqube:6.7.1
    restart: unless-stopped
    environment:
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=v07IGCFCF83Z95NX
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5431/sonarqube
    ports:
      - "9000:9000"
      - "9092:9092"
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins

  db:
    image: postgres:10.1
    restart: unless-stopped
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=v07IGCFCF83Z95NX
      - POSTGRES_DB=sonarqube
    volumes:
      - sonarqube_db:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

volumes:
  postgresql_data:
  sonarqube_bundled-plugins:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_db:
  sonarqube_extensions: